name: hogarencuba
description: Aplicación desarrollada por Daxslab.
publish_to: "none"

version: 1.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_flavor: ^1.1.1
  dio: ^3.0.10
  rxdart: ^0.24.1
  font_awesome_flutter: ^8.10.0
  cached_network_image: ^2.3.3
  localstorage: ^3.0.3+6
  url_launcher: ^5.7.5
  toast: ^0.1.5
  flutter_html: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  flutter_launcher_name: ^0.0.1

flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true

flutter_launcher_name:
  name: "HogarEnCuba"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
