name: hogarencuba
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  rxdart: ^0.23.1
  font_awesome_flutter: ^8.8.1
  cached_network_image: ^2.0.0
  localstorage: ^3.0.1+4
#  url_launcher: ^5.4.2
  toast: ^0.1.5
  flutter_html: ^0.11.1
  flutter_flavor: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - assets/images/